language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.10"
branches:
  except:
    - piptools-ignore-patch
install:
  - "pip install -U setuptools pip wheel"
  - "pip install cram"
  - "pip install ."
script:
  - "cram --shell=/bin/bash tests/*.t"
